version: "3.3"
services:
  database:
    image: "questdb/questdb"
    ports:
      - "9000:9000" # REST API, web console
      - "8812:8812" # Postgres
      - "9009:9009" # influxdb line protocol
    volumes:
      - ./data:/root/.questdb/db
    # override configuration via environemnt variables
    # https://questdb.io/docs/reference/configuration#environment-variables
    # environment: 
    #   QDB_PG_USER : admin
    #   QDB_PG_PASSWORD : quest

  # enable web server
  # web:
  #   build: .
  #   ports:
  #     - "9988:9988"
  #   volumes: 
  #     - ./web:/maro_vis
